[project]
name = "jobnexus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "linkedin-scraper>=3.1.0",
    "python-jobspy>=1.1.82",
]
